### ISSUE TITLE
Problem when hovering over tabs

### ISSUE THREAD

**Issue by arielstkl** [wilfredwee/photon-australis#16]
Hi! so far loving this project, but I noticed that when hovering over a tab it keeps focus on the active tab for a couple of pixels. Im not very good at explaining since english is not my first language, so I hope that the screenshots that I've attached get my point across.

Cheers!

![firefox error](https://user-images.githubusercontent.com/13523984/32954437-dbadc9e8-cb91-11e7-99dc-3e0592529deb.png)

![firefox error2](https://user-images.githubusercontent.com/13523984/32954440-de47d5ea-cb91-11e7-8ca6-0e092b339f12.png)

**Comment by wilfredwee** [comment]
Thanks for the feedback!

Yeah I understand what you mean. That's due to how the tabs are sized. Fixing this is a possible enhancement.

**Comment by GM-Script-Writer-62850** [comment]
Workaround:
```
#tabbrowser-tabs .tabbrowser-tab:not([selected="true"]) .close-icon{ /* Move close button over so all of it is clickable */
	margin-right:6px!important;
}
#tabbrowser-tabs .tabbrowser-tab:not(:hover):not([selected="true"]) .close-icon{ /* Only show close button on mouse over, unless it is the active tab */
	display:none;
}
```

**Comment by wilfredwee** [comment]
Better late than never, this is fixed as of https://github.com/wilfredwee/photon-australis/tree/v0.4.0

Thanks!

**Comment by Yaron10** [comment]
Hello @wilfredwee,

The problem still exists when moving the mouse from one *not-selected* tab to another *not-selected* tab.

Could you please have a look?
Thank you.

**Comment by wilfredwee** [comment]
Hi, thanks for noticing this! You are right, it is still a problem in that case. I'll reopen this issue and fix this when I have some time.

**Comment by teijiIshida** [comment]
This is fixed for me with the following changes below. It works on all tab edges: active, inactive, hover, or pinned.

Instead of 
```
.tab-background[selected="true"] {
  border: none !important;
  pointer-events: none !important;
}
```

Use
```
/* Allow correct tab to be selected near the edges */
.tab-background {
  pointer-events: none !important;
}
```

**Comment by Yaron10** [comment]
Hello,

Thanks for replying and for the fix. :+1: 
Great.

Happy New Year.

**Comment by wilfredwee** [comment]
Thanks! The fix works well. I have pushed the fix in the latest release: https://github.com/wilfredwee/photon-australis/releases/tag/v0.7

**Comment by Yaron10** [comment]
:+1:
